[build-system]
requires = ["setuptools==63.4.3"]
build-backend = "setuptools.build_meta"

[project]
name = "autcli"
version = "0.0.1"
description = "A command-line RPC client for Autonity"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "Robert Sams", email = "rs@clearmatics.com" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
  "docopt==0.6.2",
  "schema==0.7.5",
  "click==8.1.3",
]

[project.optional-dependencies]
"dev" = [
  "mypy==0.982",
  "pylint==2.15.4",
  "flake8==5.0.4",
  "black==22.3.0",
]

[project.scripts]
aut_ = "autcli.__main__:cli"
aut = "autcli.__main__:aut"

[project.urls]
Homepage = "http://github.com/clearmatics/autcli"

[tool.black]
